apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web
  labels:
    app  : my-web
    env  : prod
    owner: Dmitriy
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name : cia-web
          image: dpudovkin84/my_docker_hub:tagVersion
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
     env  : prod
     owner: Dmitriy
spec:
  type: NodePort
  selector:
    color: blue
  ports:
    - name      : my-http
      protocol  : TCP
      port      : 80
      targetPort: 80

    - name      : my-http-alt
      protocol  : TCP
      port      : 8080
      targetPort: 8080



